// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzePlaylist(arg1:string):Promise<main.PlaylistResult>;

export function CancelDownload():Promise<void>;

export function DownloadVideo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
