// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePlaylist(arg1) {
  return window['go']['main']['App']['AnalyzePlaylist'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function DownloadVideo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2, arg3, arg4);
}
